Repository boostcampwm-2022/web25-SCOPA, pull requests merged in 2022-12, with the labels that each got.

#93 [Test] Like 도메인 unit test 코드 작성
  server/package-lock.json
  server/package.json
  server/src/common/response/error-response.ts
  server/src/like/entities/like.entity.ts
  server/src/like/like.controller.spec.ts
  server/src/like/like.repository.spec.ts
  server/src/like/like.repository.ts
  server/src/like/like.service.spec.ts
  server/src/like/like.service.ts
  server/src/user/user.service.spec.ts
  server/src/user/user.service.ts
Labels: BE, test

#96 [Refactor] 회원가입 화면 코드 리팩토링
  client/src/pages/RegisterPage/IdInput.tsx
  client/src/pages/RegisterPage/constants.ts
  client/src/pages/RegisterPage/idInput.styles.ts
  client/src/pages/RegisterPage/index.tsx
  client/src/pages/RegisterPage/service.ts
  client/src/pages/RegisterPage/util.ts
  client/src/utils/constants.ts
Labels: FE, refactor

#102 [Test] User 도메인 통합 테스트
  server/package-lock.json
  server/package.json
  server/src/test/mongo.ts
  server/src/test/stub.ts
  server/src/user/dto/create-user.dto.ts
  server/src/user/user.controller.spec.ts
  server/src/user/user.controller.ts
  server/src/user/user.integration.spec.ts
  server/src/user/user.repository.spec.ts
  server/src/user/user.service.spec.ts
Labels: BE, test

#103 [Test] Like 도메인 통합 테스트
  server/src/like/like.controller.ts
  server/src/like/like.integration.spec.ts
Labels: BE, test

#107 [Feat] 로그아웃 기능 추가
  server/src/auth/auth.controller.ts
  server/src/user/dto/create-user.dto.ts
  server/src/user/user.integration.spec.ts
Labels: feat, BE

#106 [Feat] FE. 코드 에디터 추가
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/common/CodeBox/styles.ts
  client/src/common/CommonLayout/Header.tsx
  client/src/common/index.ts
  client/src/hooks/useCheckLogin.ts
  client/src/pages/DetailPage/EditModeContainer/BottomProfileEditor.styles.ts
  client/src/pages/DetailPage/EditModeContainer/BottomProfileEditor.tsx
  client/src/pages/DetailPage/EditModeContainer/CodeEditor.styles.ts
  client/src/pages/DetailPage/EditModeContainer/CodeEditor.tsx
  client/src/pages/DetailPage/EditModeContainer/TopProfileEditor.styles.ts
  client/src/pages/DetailPage/EditModeContainer/TopProfileEditor.tsx
  client/src/pages/DetailPage/EditModeContainer/index.tsx
  client/src/pages/DetailPage/EditModeContainer/styles.ts
  client/src/pages/DetailPage/EditModeContainer/useSetProfileEditor.ts
  client/src/pages/DetailPage/ViewModeContainer/BottomProfileBox.styles.ts
  client/src/pages/DetailPage/ViewModeContainer/BottomProfileBox.tsx
  client/src/pages/DetailPage/ViewModeContainer/InterestBadge/constants.ts
  client/src/pages/DetailPage/ViewModeContainer/InterestBadge/index.tsx
  client/src/pages/DetailPage/ViewModeContainer/InterestBadge/styles.ts
  client/src/pages/DetailPage/ViewModeContainer/TechStackBadge/index.tsx
  client/src/pages/DetailPage/ViewModeContainer/TechStackBadge/styles.ts
  client/src/pages/DetailPage/ViewModeContainer/TopProfileBox.styles.ts
  client/src/pages/DetailPage/ViewModeContainer/TopProfileBox.tsx
  client/src/pages/DetailPage/ViewModeContainer/index.tsx
  client/src/pages/DetailPage/ViewModeContainer/styles.ts
  client/src/pages/DetailPage/index.tsx
  client/src/pages/DetailPage/mockData.ts
  client/src/pages/MainPage/Profile.tsx
  client/src/pages/MainPage/mockData.ts
  client/src/pages/MainPage/service.ts
  client/src/pages/MainPage/types.ts
  client/src/pages/Mypage/EditModeContainer/CodeEditor.styles.ts
  client/src/pages/Mypage/EditModeContainer/CodeEditor.tsx
  client/src/pages/Mypage/index.tsx
  client/src/pages/Mypage/mockData.ts
  client/src/pages/Mypage/styles.ts
  client/src/pages/index.ts
  client/src/services/fetchCheckLogin.ts
  client/src/types/profile.d.ts
  client/src/utils/constants.ts
  server/src/user/dto/find-user.dto.ts
  server/src/user/dto/page-user.dto.ts
  server/src/user/dto/update-user.dto.ts
  server/src/user/user.controller.ts
Labels: feat, FE, design

#109 [Feat] BE. 프로필 관련 api 구현
  server/package-lock.json
  server/package.json
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/common/d.ts
  server/src/common/enum.ts
  server/src/common/http-execption-filter.ts
  server/src/common/response/error-response.ts
  server/src/like/dto/add-like.dto.ts
  server/src/like/dto/delete-like.dto.ts
  server/src/like/like.controller.spec.ts
  server/src/like/like.controller.ts
  server/src/like/like.integration.spec.ts
  server/src/like/like.repository.spec.ts
  server/src/like/like.repository.ts
  server/src/like/like.service.spec.ts
  server/src/like/like.service.ts
  server/src/test/stub.ts
  server/src/user/dto/create-user.dto.ts
  server/src/user/dto/find-user.dto.ts
  server/src/user/dto/page-user.dto.ts
  server/src/user/dto/pagination.ts
  server/src/user/dto/update-user.dto.ts
  server/src/user/entities/user.entity.ts
  server/src/user/user.controller.spec.ts
  server/src/user/user.controller.ts
  server/src/user/user.integration.spec.ts
  server/src/user/user.repository.spec.ts
  server/src/user/user.repository.ts
  server/src/user/user.service.spec.ts
  server/src/user/user.service.ts
Labels: feat, BE

#112 [Feat]FE. 메인화면 프로필 코드박스 적용
  client/src/pages/MainPage/Profile.tsx
  client/src/pages/MainPage/SummarizedCodeBox.tsx
  client/src/pages/MainPage/index.tsx
  client/src/pages/MainPage/service.ts
  client/src/pages/MainPage/styles.ts
  client/src/pages/RegisterPage/service.ts
  client/src/pages/RegisterPage/util.ts
Labels: feat, FE

#115 [Fix] BE. 유저 정보 변경 조건문 수정
  server/src/main.ts
  server/src/user/user.service.spec.ts
  server/src/user/user.service.ts
Labels: bug, BE

#117 [Fix] BE. 회원가입 오류 수정
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/common/d.ts
  server/src/user/user.controller.spec.ts
  server/src/user/user.integration.spec.ts
  server/src/user/user.service.spec.ts
Labels: bug, BE

#121 [Fix] FE. 오류 핫픽스
  client/src/common/CodeBox/index.tsx
  client/src/pages/DetailPage/DetailPageInner.tsx
  client/src/pages/DetailPage/EditModeContainer/useSetProfileEditor.ts
  client/src/pages/MainPage/Profile.tsx
Labels: FE, problem

#124 [Refactor] FE. 성능개선 및 메인화면 기능동작 수정
  client/src/common/Button/index.tsx
  client/src/common/CommonLayout/Header.styles.ts
  client/src/common/CommonLayout/Header.tsx
  client/src/common/DropdownInput/InterestInput.tsx
  client/src/common/DropdownInput/TechStackInput.tsx
  client/src/common/LoginLayout/index.tsx
  client/src/pages/MainPage/index.tsx
  client/src/pages/MainPage/styles.ts
  client/src/pages/RegisterPage/IdInput.tsx
  client/src/pages/RegisterPage/index.tsx
  client/src/styles/sizes.ts
Labels: FE, refactor

#126 [Fix] FE. 핫픽스 및 편집페이지 유저명 검증 기능 추가, 메인 페이지 관심분야 태그 추가 등
  client/README.md
  client/public/index.html
  client/src/assets/svgs/errorIcon.svg
  client/src/assets/svgs/index.ts
  client/src/assets/svgs/labelIcon.svg
  client/src/assets/svgs/questionIcon.svg
  client/src/common/CodeBox/styles.ts
  client/src/common/CommonLayout/Header.tsx
  client/src/common/DropdownInput/SelectedItems.styles.ts
  client/src/common/DropdownInput/TechStackBox.styles.ts
  client/src/common/DropdownInput/TechStackInput.tsx
  client/src/common/LoginLayout/index.tsx
  client/src/common/Tooltip/index.tsx
  client/src/common/Tooltip/styles.ts
  client/src/common/index.ts
  client/src/hooks/index.ts
  client/src/hooks/useLoadSettings.ts
  client/src/hooks/useShowTooltip.ts
  client/src/hooks/useValidateUsername.ts
  client/src/pages/DetailPage/DetailPageInner.tsx
  client/src/pages/DetailPage/EditModeContainer/BottomProfileEditor.tsx
  client/src/pages/DetailPage/EditModeContainer/CodeEditor.tsx
  client/src/pages/DetailPage/EditModeContainer/NavBarInner.styles.ts
  client/src/pages/DetailPage/EditModeContainer/NavBarInner.tsx
  client/src/pages/DetailPage/EditModeContainer/index.tsx
  client/src/pages/DetailPage/EditModeContainer/styles.ts
  client/src/pages/DetailPage/EditModeContainer/useSetProfileEditor.ts
  client/src/pages/DetailPage/ViewModeContainer/BottomProfileBox.tsx
  client/src/pages/DetailPage/ViewModeContainer/InterestBadge/constants.ts
  client/src/pages/DetailPage/ViewModeContainer/InterestBadge/index.tsx
  client/src/pages/DetailPage/ViewModeContainer/InterestBadge/styles.ts
  client/src/pages/DetailPage/ViewModeContainer/TechStackBadge/styles.ts
  client/src/pages/DetailPage/ViewModeContainer/TopProfileBox.styles.ts
  client/src/pages/DetailPage/ViewModeContainer/index.tsx
  client/src/pages/DetailPage/ViewModeContainer/styles.ts
  client/src/pages/MainPage/InterestTag.styles.ts
  client/src/pages/MainPage/InterestTag.tsx
  client/src/pages/MainPage/Profile.styles.ts
  client/src/pages/MainPage/Profile.tsx
  client/src/pages/MainPage/ProfileList.tsx
  client/src/pages/MainPage/fetchFilteredData.ts
  client/src/pages/MainPage/index.tsx
  client/src/pages/MainPage/service.ts
  client/src/pages/MainPage/styles.ts
  client/src/pages/MainPage/types.ts
  client/src/pages/RegisterPage/IdInput.tsx
  client/src/pages/RegisterPage/constants.ts
  client/src/pages/RegisterPage/fetchRequestRegistration.ts
  client/src/pages/RegisterPage/index.tsx
  client/src/pages/RegisterPage/usernameInput.styles.ts
  client/src/pages/RegisterPage/usernameInput.tsx
  client/src/pages/SettingsPage/CodeBoxSelector.styles.ts
  client/src/pages/SettingsPage/index.tsx
  client/src/pages/SettingsPage/styles.ts
  client/src/reset.css
  client/src/services/fetchSendLikeToServer.ts
  client/src/services/fetchUsernameServerValidation.ts
  client/src/services/index.ts
  client/src/utils/constants.ts
  client/src/utils/usernameValidation.ts
Labels: bug, feat, FE, design

#120 [Feat] BE. 메시지 API
  server/src/app.module.ts
  server/src/like/like.service.ts
  server/src/message/dto/send-message.dto.ts
  server/src/message/entities/content.entity.ts
  server/src/message/entities/message.entity.ts
  server/src/message/message.controller.spec.ts
  server/src/message/message.controller.ts
  server/src/message/message.integration.spec.ts
  server/src/message/message.module.ts
  server/src/message/message.repository.spec.ts
  server/src/message/message.repository.ts
  server/src/message/message.service.spec.ts
  server/src/message/message.service.ts
  server/src/test/stub.ts
  server/src/user/dto/create-user.dto.ts
  server/src/user/dto/update-user.dto.ts
  server/src/user/entities/user.entity.ts
  server/src/user/user.controller.ts
  server/src/user/user.integration.spec.ts
  server/src/user/user.repository.spec.ts
  server/src/user/user.repository.ts
  server/src/user/user.service.spec.ts
  server/src/user/user.service.ts
Labels: feat, BE, test

#130 [Fix] 좋아요 관련 수정 및 업데이트 값 검증
  client/src/pages/DetailPage/DetailPageInner.tsx
  client/src/pages/DetailPage/ViewModeContainer/index.tsx
  client/src/pages/DetailPage/index.tsx
  client/src/pages/MainPage/Profile.tsx
  client/src/pages/MainPage/fetchFilteredData.ts
  client/src/pages/MainPage/index.tsx
  server/src/auth/auth.controller.ts
  server/src/user/dto/update-user.dto.ts
Labels: bug, BE, FE

#134 [Feat] FE/BE. SSE 기본 동작 테스트 완료
  client/src/App.tsx
  client/src/hooks/index.ts
  client/src/hooks/useSetSSE.ts
  client/src/pages/MessagePage/MessageDetail/MessageDetailInner.tsx
  client/src/pages/MessagePage/MessageDetail/index.tsx
  client/src/pages/MessagePage/services/fetchMessageDetail.ts
  client/src/pages/MessagePage/services/fetchSendMessage.ts
  client/src/pages/MessagePage/services/index.ts
  client/src/utils/constants.ts
  server/src/message/entities/message.entity.ts
  server/src/message/message.controller.ts
  server/src/message/message.service.ts
Labels: feat, BE, FE

#135 [Fix] BE. 기타 오류 수정
  client/src/App.tsx
  client/src/hooks/index.ts
  client/src/hooks/useSetSSE.ts
  client/src/pages/MessagePage/MessageDetail/MessageDetailInner.tsx
  client/src/pages/MessagePage/MessageDetail/index.tsx
  client/src/pages/MessagePage/services/fetchMessageDetail.ts
  client/src/pages/MessagePage/services/fetchSendMessage.ts
  client/src/pages/MessagePage/services/index.ts
  client/src/utils/constants.ts
  server/src/auth/auth.controller.ts
  server/src/message/entities/message.entity.ts
  server/src/message/message.controller.ts
  server/src/message/message.service.ts
  server/src/user/dto/pagination.ts
  server/src/user/dto/update-user.dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.integration.spec.ts
Labels: bug, BE

#138 [Refactor]FE. 메인화면 필터링 기능 및 디자인 수정
  client/src/pages/MainPage/Profile.styles.ts
  client/src/pages/MainPage/ProfileList.tsx
  client/src/pages/MainPage/fetchFilteredData.ts
  client/src/pages/MainPage/index.tsx
  client/src/styles/sizes.ts
Labels: FE, refactor

#136 [Feat] FE/BE. SSE 쪽지 기능 추가 및 API 연결
  client/src/common/Button.tsx
  client/src/common/CommonLayout/Header.styles.ts
  client/src/common/CommonLayout/Header.tsx
  client/src/common/DropdownInput/SelectedItems.styles.ts
  client/src/hooks/useSetSSE.ts
  client/src/pages/DetailPage/services/fetchUserData.ts
  client/src/pages/MainPage/Profile.tsx
  client/src/pages/MainPage/ProfileList.tsx
  client/src/pages/MainPage/index.tsx
  client/src/pages/MainPage/types.ts
  client/src/pages/MainPage/useSetMainPageData.ts
  client/src/pages/MessagePage/MessageDetail/MessageDetailInner.tsx
  client/src/pages/MessagePage/MessageDetail/MessageElement.styles.ts
  client/src/pages/MessagePage/MessageDetail/MessageElement.tsx
  client/src/pages/MessagePage/MessageDetail/index.tsx
  client/src/pages/MessagePage/MessageDetail/styles.ts
  client/src/pages/MessagePage/MessageList.tsx
  client/src/pages/MessagePage/hooks/index.ts
  client/src/pages/MessagePage/hooks/useManageMessageData.ts
  client/src/pages/MessagePage/hooks/useScrollBottom.ts
  client/src/pages/MessagePage/index.tsx
  client/src/pages/MessagePage/services/fetchMessageDetail.ts
  client/src/pages/MessagePage/services/fetchMessageList.ts
  client/src/store/index.ts
  client/src/store/isNewMessageState.ts
  client/src/store/newMessageState.ts
  client/src/types/message.d.ts
  client/src/types/profile.d.ts
  client/src/types/test.d.ts
  client/src/utils/constants.ts
  server/src/message/message.controller.spec.ts
  server/src/message/message.controller.ts
  server/src/message/message.integration.spec.ts
  server/src/message/message.service.ts
  server/src/user/entities/user.entity.ts
  server/src/user/user.repository.ts
  server/src/user/user.service.ts
Labels: feat, BE, FE, design

#139 [Design]FE. 메인화면 반응형디자인 수정
  client/src/pages/MainPage/Profile.styles.ts
  client/src/pages/MainPage/styles.ts
  client/src/styles/sizes.ts
Labels: FE, design

#140 [Fix] FE. 회원가입 페이지 오버플로우 hidden 제거, 좋아요 유지 안되는 문제 수정
  client/src/common/LoginLayout.tsx
  client/src/pages/DetailPage/ViewModeContainer/index.tsx
  client/src/pages/MainPage/Profile.tsx
Labels: bug, FE, design

#141 [Test] Auth test 작성, email 속성 수정 및 리팩토링
  client/src/types/profile.d.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.integration.spec.ts
  server/src/auth/auth.service.ts
  server/src/common/d.ts
  server/src/like/like.controller.ts
  server/src/like/like.integration.spec.ts
  server/src/main.ts
  server/src/message/message.integration.spec.ts
  server/src/test/mongo.ts
  server/src/test/stub.ts
  server/src/user/dto/update-user.dto.ts
  server/src/user/entities/user.entity.ts
  server/src/user/user.controller.spec.ts
  server/src/user/user.integration.spec.ts
  server/src/user/user.service.spec.ts
Labels: BE, refactor, test
