Repository boostcampwm-2022/web25-SCOPA, pull requests merged in 2022-11, with the labels that each got.

#13 [chore] FE. 구조 설계 및 공용 CSS 설정 완료
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/public/loginBG.jpg
  client/src/App.css
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/assets/svgs/arrowDownIcon.svg
  client/src/assets/svgs/githubIcon.svg
  client/src/assets/svgs/googleIcon.svg
  client/src/assets/svgs/heartEmptyIcon.svg
  client/src/assets/svgs/heartFilledIcon.svg
  client/src/assets/svgs/index.ts
  client/src/assets/svgs/pencilIcon.svg
  client/src/common/InterestsBox/index.tsx
  client/src/common/TechStackBox/index.tsx
  client/src/common/index.ts
  client/src/index.css
  client/src/index.tsx
  client/src/pages/LoginPage/index.tsx
  client/src/pages/RegisterPage/index.tsx
  client/src/pages/index.ts
  client/src/reportWebVitals.ts
  client/src/reset.css
  client/src/services/index.ts
  client/src/setupTests.ts
  client/src/store/index.ts
  client/src/styles/colors.ts
  client/src/styles/sizes.ts
  client/src/types/test.d.ts
Labels: FE, structure

#15 [feat] BE. Github OAuth 를 통한 사용자 이메일 정보 받아오기
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/main.ts
Labels: feat, BE

#19 Feat: Github Actions 를 이용한 CD 환경 설정
  .github/workflows/deploy.yml
  server/ecosystem.config.js
  server/package.json
Labels: feat, BE

#21 [feat] BE.ci script 작성
  .github/workflows/be-ci.yml
  .github/workflows/deploy.yml
  server/package.json
  server/src/auth/auth.controller.ts
Labels: feat, BE

#23 [feat] FE. 로그인 페이지 및 공용 컴포넌트 추가
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/browserconfig.xml
  client/public/earlybird.png
  client/public/favicons/android-icon-144x144.png
  client/public/favicons/android-icon-192x192.png
  client/public/favicons/android-icon-36x36.png
  client/public/favicons/android-icon-48x48.png
  client/public/favicons/android-icon-72x72.png
  client/public/favicons/android-icon-96x96.png
  client/public/favicons/apple-icon-114x114.png
  client/public/favicons/apple-icon-120x120.png
  client/public/favicons/apple-icon-144x144.png
  client/public/favicons/apple-icon-152x152.png
  client/public/favicons/apple-icon-180x180.png
  client/public/favicons/apple-icon-57x57.png
  client/public/favicons/apple-icon-60x60.png
  client/public/favicons/apple-icon-72x72.png
  client/public/favicons/apple-icon-76x76.png
  client/public/favicons/apple-icon-precomposed.png
  client/public/favicons/apple-icon.png
  client/public/favicons/favicon-16x16.png
  client/public/favicons/favicon-32x32.png
  client/public/favicons/favicon-96x96.png
  client/public/favicons/favicon.ico
  client/public/favicons/ms-icon-144x144.png
  client/public/favicons/ms-icon-150x150.png
  client/public/favicons/ms-icon-310x310.png
  client/public/favicons/ms-icon-70x70.png
  client/public/index.html
  client/public/manifest.json
  client/src/App.tsx
  client/src/common/CheckLogin/index.tsx
  client/src/common/LoginLayout/index.tsx
  client/src/common/LoginLayout/styles.ts
  client/src/common/TechStackBox/TechStackCheckbox.styles.ts
  client/src/common/TechStackBox/TechStackCheckbox.tsx
  client/src/common/TechStackBox/createLinearGradient.ts
  client/src/common/TechStackBox/index.tsx
  client/src/common/TechStackBox/styles.ts
  client/src/common/index.ts
  client/src/index.tsx
  client/src/pages/LoginPage/LoginButtonComponent.styles.ts
  client/src/pages/LoginPage/LoginButtonComponent.tsx
  client/src/pages/LoginPage/index.tsx
  client/src/pages/LoginPage/styles.ts
  client/src/pages/MainPage/index.tsx
  client/src/pages/TestPage/index.tsx
  client/src/pages/index.ts
  client/src/reset.css
  client/src/store/currentUserState.ts
  client/src/store/index.ts
  client/src/styles/colors.ts
  client/src/styles/sizes.ts
  client/src/types/auth.d.ts
  client/src/utils/constants.ts
  client/tsconfig.json
Labels: feat, FE, design

#32 [Feat] /api/auth/check & /api/auth/validate API 작성
  server/package-lock.json
  server/package.json
  server/src/auth/auth.controller.ts
  server/src/main.ts
Labels: feat, BE

#30 [Feat] FE. 회원가입화면 레이아웃 및 로직 일부 구현
  client/src/App.tsx
  client/src/common/InterestsBox/index.tsx
  client/src/common/InterestsBox/styles.ts
  client/src/pages/LoginPage/index.tsx
  client/src/pages/RegisterPage/IdInput/index.tsx
  client/src/pages/RegisterPage/InterestInput/index.tsx
  client/src/pages/RegisterPage/SelectedItems.tsx
  client/src/pages/RegisterPage/TechStackInput/index.tsx
  client/src/pages/RegisterPage/index.tsx
  client/src/pages/RegisterPage/styles.ts
  client/src/store/index.ts
Labels: 리뷰요청, feat, FE

#31 [Feat] FE. 로그인 화면 개선
  client/src/common/CheckLogin/index.tsx
  client/src/common/TechStackBox/TechStackCheckbox.tsx
  client/src/common/TechStackBox/index.tsx
  client/src/hooks/index.ts
  client/src/hooks/useClickOutside.ts
Labels: FE, refactor

#34 [Feat] FE. 회원가입화면 로직 일부 구현 및 리뷰사항 반영
  client/src/common/InterestsBox/styles.ts
  client/src/pages/RegisterPage/IdInput/index.tsx
  client/src/pages/RegisterPage/InterestInput/index.tsx
  client/src/pages/RegisterPage/TechStackInput/index.tsx
  client/src/pages/RegisterPage/index.tsx
  client/src/pages/RegisterPage/styles.ts
  client/src/store/index.ts
Labels: FE

#33 [Feat] FE. 메인 페이지 레이아웃
  client/src/App.tsx
  client/src/common/CommonLayout/NavigationBar.styles.ts
  client/src/common/CommonLayout/NavigationBar.tsx
  client/src/common/CommonLayout/index.tsx
  client/src/common/CommonLayout/styles.ts
  client/src/common/MiniNavBar/index.tsx
  client/src/common/MiniNavBar/styles.ts
  client/src/common/TechStackBox/index.tsx
  client/src/common/index.ts
  client/src/pages/LoginPage/index.tsx
  client/src/pages/MainPage/index.tsx
  client/src/pages/RegisterPage/TechStackInput/index.tsx
  client/src/reset.css
  client/src/styles/sizes.ts
Labels: feat, FE, design

#35 [Feat] FE. 회원가입화면
  client/src/common/InterestsBox/index.tsx
  client/src/common/TechStackBox/styles.ts
  client/src/pages/RegisterPage/IdInput.tsx
  client/src/pages/RegisterPage/InterestInput.tsx
  client/src/pages/RegisterPage/InterestInput/index.tsx
  client/src/pages/RegisterPage/SelectedItems.tsx
  client/src/pages/RegisterPage/TechStackInput.tsx
  client/src/pages/RegisterPage/index.tsx
  client/src/pages/RegisterPage/styles.ts
  client/src/pages/TestPage/index.tsx
  client/src/utils/constants.ts
Labels: feat, FE

#37 [Feat] FE. 회원가입 정보 전송 기능 구현
  client/src/assets/svgs/index.ts
  client/src/assets/svgs/xIcon.svg
  client/src/common/InterestsBox/index.tsx
  client/src/pages/RegisterPage/IdInput.tsx
  client/src/pages/RegisterPage/InterestInput.tsx
  client/src/pages/RegisterPage/SelectedItems.tsx
  client/src/pages/RegisterPage/TechStackInput.tsx
  client/src/pages/RegisterPage/index.tsx
  client/src/pages/RegisterPage/styles.ts
Labels: feat, FE

#38 [Feat] BE. mongoose를 통한 mongoDB Atlas 연동 설정
  .gitignore
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/app.controller.spec.ts
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/app.service.ts
  server/src/auth/auth.controller.spec.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.spec.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/update-auth.dto.ts
  server/src/auth/entities/auth.entity.ts
  server/src/d.ts
  server/src/main.ts
Labels: feat, BE

#42 [Refactor] 회원가입화면 아이디 유효성 경고 방식 수정
  client/src/pages/RegisterPage/IdInput.tsx
  client/src/pages/RegisterPage/index.tsx
  client/src/pages/RegisterPage/styles.ts
Labels: FE, refactor

#44 [Feat] FE. 컴포넌트 최상위에 로그인 검증 로직 추가
  client/src/common/CheckLogin/index.tsx
  client/src/common/CommonLayout/NavigationBar.tsx
  client/src/common/LoginLayout/index.tsx
  client/src/pages/LoginPage/index.tsx
  client/src/services/fetchCheckLogin.ts
  client/src/services/index.ts
  client/src/store/currentUserState.ts
  client/src/types/auth.d.ts
  client/src/utils/constants.ts
Labels: feat, FE

#45 [Feat] 회원가입 api 추가
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/create-auth.dto.ts
  server/src/auth/dto/update-auth.dto.ts
  server/src/d.ts
  server/src/main.ts
  server/src/user/dto/create-user.dto.ts
  server/src/user/dto/update-user.dto.ts
  server/src/user/entities/user.entity.ts
  server/src/user/user.controller.spec.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.spec.ts
  server/src/user/user.service.ts
Labels: feat, BE

#47 [Fix] 회원가입화면 서버 통신 관련 수정
  client/src/pages/RegisterPage/IdInput.tsx
  client/src/pages/RegisterPage/index.tsx
  client/src/utils/constants.ts
  server/src/user/user.controller.ts
Labels: bug, FE

#48 [Fix] 로그인 체크 로직 수정
  client/src/App.tsx
  client/src/common/CheckLogin/index.tsx
  client/src/index.tsx
  client/src/services/fetchCheckLogin.ts
Labels: bug, FE

#51 [Refactor] 회원 가입 기능 리팩토링
  client/src/pages/RegisterPage/index.tsx
  server/src/auth/auth.controller.ts
  server/src/user/dto/create-user.dto.ts
  server/src/user/dto/update-user.dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
Labels: BE, refactor

#55 [Feat] BE. 응답 성공, 실패 객체 정의
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/common/http-execption-filter.ts
  server/src/common/response/error-response.ts
  server/src/common/response/success-response.ts
  server/src/d.ts
  server/src/main.ts
  server/src/user/user.controller.spec.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.spec.ts
Labels: feat, BE

#50 [Feat] FE. 상세 페이지 레이아웃 잡기
  client/src/App.tsx
  client/src/common/CommonLayout/NavigationBar.styles.ts
  client/src/common/CommonLayout/NavigationBar.tsx
  client/src/common/CommonLayout/styles.ts
  client/src/common/InterestsBox/styles.ts
  client/src/pages/DetailPage/BottomProfileBox.styles.ts
  client/src/pages/DetailPage/BottomProfileBox.tsx
  client/src/pages/DetailPage/CodeBox.styles.ts
  client/src/pages/DetailPage/CodeBox.tsx
  client/src/pages/DetailPage/TopProfileBox.styles.ts
  client/src/pages/DetailPage/TopProfileBox.tsx
  client/src/pages/DetailPage/index.tsx
  client/src/pages/DetailPage/styles.ts
  client/src/pages/MainPage/index.tsx
  client/src/pages/RegisterPage/SelectedItems.tsx
  client/src/pages/RegisterPage/styles.ts
  client/src/pages/index.ts
  client/src/reset.css
  client/src/styles/sizes.ts
Labels: feat, FE, design

#67 [Feat] FE. 메인화면 레이아웃 구현
  client/src/assets/svgs/heartEmptyIcon.svg
  client/src/assets/svgs/heartFilledIcon.svg
  client/src/assets/svgs/index.ts
  client/src/assets/svgs/searchIcon.svg
  client/src/common/CommonLayout/styles.ts
  client/src/common/SelectedItems/index.tsx
  client/src/common/SelectedItems/styles.ts
  client/src/common/index.ts
  client/src/pages/MainPage/InterestFilter.tsx
  client/src/pages/MainPage/Profile.tsx
  client/src/pages/MainPage/ProfileList.tsx
  client/src/pages/MainPage/SummarizedCodeBox.tsx
  client/src/pages/MainPage/TechStackFilter.tsx
  client/src/pages/MainPage/index.tsx
  client/src/pages/MainPage/mockData.ts
  client/src/pages/MainPage/styles.ts
  client/src/pages/MainPage/types.ts
  client/src/pages/RegisterPage/TechStackInput.tsx
  client/src/pages/RegisterPage/styles.ts
  client/src/styles/colors.ts
  client/src/styles/sizes.ts
Labels: feat, FE

#70 [Feat] 좋아요 관련 api 구현
  server/src/app.module.ts
  server/src/auth/auth.controller.spec.ts
  server/src/like/dto/add-like.dto.ts
  server/src/like/dto/delete-like.dto.ts
  server/src/like/entities/like.entity.ts
  server/src/like/like.controller.spec.ts
  server/src/like/like.controller.ts
  server/src/like/like.module.ts
  server/src/like/like.repository.ts
  server/src/like/like.service.spec.ts
  server/src/like/like.service.ts
  server/src/user/dto/create-user.dto.ts
  server/src/user/user.module.ts
  server/src/user/user.repository.ts
  server/src/user/user.service.ts
Labels: feat, BE

#71 [Feat] FE. 회원가입화면 서버측 ID유효성 검사 결과 안내
  client/src/pages/RegisterPage/IdInput.tsx
  client/src/pages/RegisterPage/styles.ts
  client/src/utils/constants.ts
Labels: feat, FE

#74 [Design] FE. 메인화면 레이아웃 디자인 일부 수정
  client/src/assets/svgs/emptyHeartIcon.svg
  client/src/assets/svgs/filledHeartIcon.svg
  client/src/assets/svgs/index.ts
  client/src/common/SelectedItems/styles.ts
  client/src/pages/MainPage/InterestFilter.tsx
  client/src/pages/MainPage/Profile.tsx
  client/src/pages/MainPage/TechStackFilter.tsx
  client/src/pages/MainPage/styles.ts
Labels: FE, design

#75 [Fix] BE. 회원 가입 오류 수정
  client/src/pages/RegisterPage/index.tsx
  client/src/utils/constants.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/common/http-execption-filter.ts
  server/src/common/response/error-response.ts
  server/src/d.ts
  server/src/like/entities/like.entity.ts
  server/src/like/like.controller.spec.ts
  server/src/like/like.controller.ts
  server/src/like/like.module.ts
  server/src/like/like.repository.ts
  server/src/like/like.service.ts
  server/src/user/dto/create-user.dto.ts
  server/src/user/entities/user.entity.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.repository.ts
  server/src/user/user.service.ts
Labels: bug, BE

#76 [Feat] FE. 코드 에디터 페이지 작업
  client/src/App.tsx
  client/src/assets/svgs/editIcon.svg
  client/src/assets/svgs/index.ts
  client/src/assets/svgs/pencilIcon.svg
  client/src/assets/svgs/saveIcon.svg
  client/src/common/CheckLogin/index.tsx
  client/src/common/InterestsBox/index.tsx
  client/src/common/InterestsBox/styles.ts
  client/src/common/SelectedItems/styles.ts
  client/src/common/TechStackBox/index.tsx
  client/src/common/TechStackBox/styles.ts
  client/src/common/index.ts
  client/src/hooks/index.ts
  client/src/hooks/useCheckLogin.ts
  client/src/index.tsx
  client/src/pages/DetailPage/EditModeContainer/BottomProfileEditor.styles.ts
  client/src/pages/DetailPage/EditModeContainer/BottomProfileEditor.tsx
  client/src/pages/DetailPage/EditModeContainer/CodeEditor.styles.ts
  client/src/pages/DetailPage/EditModeContainer/CodeEditor.tsx
  client/src/pages/DetailPage/EditModeContainer/InterestSelector.styles.ts
  client/src/pages/DetailPage/EditModeContainer/InterestSelector.tsx
  client/src/pages/DetailPage/EditModeContainer/TechStackSelector.styles.ts
  client/src/pages/DetailPage/EditModeContainer/TechStackSelector.tsx
  client/src/pages/DetailPage/EditModeContainer/TopProfileEditor.styles.ts
  client/src/pages/DetailPage/EditModeContainer/TopProfileEditor.tsx
  client/src/pages/DetailPage/EditModeContainer/index.tsx
  client/src/pages/DetailPage/EditModeContainer/useSetProfileEditor.ts
  client/src/pages/DetailPage/ViewModeContainer/BottomProfileBox.styles.ts
  client/src/pages/DetailPage/ViewModeContainer/BottomProfileBox.tsx
  client/src/pages/DetailPage/ViewModeContainer/CodeBox.styles.ts
  client/src/pages/DetailPage/ViewModeContainer/CodeBox.tsx
  client/src/pages/DetailPage/ViewModeContainer/TopProfileBox.styles.ts
  client/src/pages/DetailPage/ViewModeContainer/TopProfileBox.tsx
  client/src/pages/DetailPage/ViewModeContainer/index.tsx
  client/src/pages/DetailPage/index.tsx
  client/src/pages/DetailPage/mockData.ts
  client/src/pages/DetailPage/styles.ts
  client/src/pages/MainPage/InterestFilter.tsx
  client/src/pages/MainPage/TechStackFilter.tsx
  client/src/pages/MainPage/styles.ts
  client/src/pages/RegisterPage/IdInput.tsx
  client/src/pages/RegisterPage/InterestInput.tsx
  client/src/pages/RegisterPage/TechStackInput.tsx
  client/src/pages/RegisterPage/styles.ts
  client/src/pages/TestPage/index.tsx
  client/src/pages/index.ts
  client/src/styles/colors.ts
  client/src/styles/sizes.ts
  client/src/types/profile.d.ts
Labels: feat, FE, design

#77 [Feat] 슬랙 알림 봇 생성
  .github/workflows/be-ci.yml
  .github/workflows/deploy.yml
  .github/workflows/slack-notify.yml
Labels: feat

#88 [Feat] BE. profile mock api 구현
  server/src/common/http-execption-filter.ts
  server/src/common/response/error-response.ts
  server/src/d.ts
  server/src/user/dto/create-user.dto.ts
  server/src/user/dto/find-user.dto.ts
  server/src/user/dto/page-user.dto.ts
  server/src/user/dto/update-user.dto.ts
  server/src/user/user.controller.ts
Labels: feat, BE, refactor

#91 [Feat] FE. 메인화면 기능 구현
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/pages/MainPage/Profile.tsx
  client/src/pages/MainPage/index.tsx
  client/src/pages/MainPage/mockData.ts
  client/src/pages/MainPage/service.ts
  client/src/pages/MainPage/styles.ts
  client/src/utils/constants.ts
Labels: feat, FE

#90 [Feat] BE. user 도메인 unit test 작성
  server/package-lock.json
  server/package.json
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/common/base-entity.ts
  server/src/common/http-execption-filter.ts
  server/src/common/response/index.ts
  server/src/like/entities/like.entity.ts
  server/src/like/like.controller.ts
  server/src/like/like.repository.ts
  server/src/like/like.service.ts
  server/src/user/dto/create-user.dto.ts
  server/src/user/entities/user.entity.ts
  server/src/user/user.controller.spec.ts
  server/src/user/user.controller.ts
  server/src/user/user.repository.spec.ts
  server/src/user/user.repository.ts
  server/src/user/user.service.spec.ts
  server/src/user/user.service.ts
Labels: BE, test
